### ISSUE TITLE
Question about wifi csv format and naming

### ISSUE THREAD

**Issue by weixijia** [benmwebb/wifi-heatmap#1]
is:issue is:open HI there, thx for the code, could you please illustrate the format of the wifi csv. Or could you please share your csv that already worked with the code then I can reformat my wifi csv to fit the code

**Comment by benmwebb** [comment]
It's a very simple format; see https://github.com/benmwebb/wifi-heatmap/blob/master/wifi-heatmap.py#L82-L89

The first two columns are the X and Y coordinates; the remaining columns are the integer RSSIs (signal strength) of each network (or blank if that network couldn't be found at that coordinate). The first row contains the column headings: "X", "Y", and "{BSSID};{SSID}" for each network.
